### PR TITLE
Fixed saturation level variation in JPEG images

### LINKED ISSUE #9: Saturation levels of original and decoded image not same
The quality of the image degrades on saving it.
There is some loss of saturation while encoding and while decoding the same happens, making the original and decoded pictures look different even though the form and pattern is recovered 100%

P.S. Happens only with `.jpg` images, `.png` images work fine

### PR DESCRIPTION
**Pull request by arulthileeban**
Fixes #9

Issue:
JPEG Images use the concept of chroma subsampling which assumes that some information can be safely disposed. This increases efficiency, but reduces quality. This tradeoff is fixed towards the end of quality here.

Changes proposed:
=> Extension is retrieved from the image path. Based on that, suitable settings are set while saving the image.
=> Settings include setting subsampling to 0 and quality to 100

### CODE REVIEW

**Comment by HarshKhatore** [comment]
Should not the quality as a parameter to im.save() be set to 95 instead of 100, for best results?

Documentation:
The image quality, on a scale from 1 (worst) to 95 (best). The default is 75. Values above 95 should be avoided; 100 disables portions of the JPEG compression algorithm and results in large files with hardly any gain in image quality.

I read it here from the documentation of im.save(): [Additional parameters to save()](http://pillow.readthedocs.io/en/3.1.x/handbook/image-file-formats.html)

**Comment by arulthileeban** [comment]
I verified this against a couple of images.Between 95 and 100 in the quality parameter, there is an increase in size by around 20-35% and drop of quality by 0.2-0.6% ( Checked using few image difference analyzers ). Hence I went ahead with 100 for complete preservation of quality. Is the difference in quality negligible enough to shift the parameter down to 95 ? If so, I ll put in a commit.

**Comment by Aniq55** [comment]
post some sample original, encoded and decoded images obtained after this change @arulthileeban 
The image width and height must remain unchaged under all conditions

**Comment by arulthileeban** [comment]
Original:
lion

Quality Parameter=95:
Encoded:
lion jpeg_en
Decoded:
lion jpeg_en jpeg_dec

Quality Parameter=100:
Encoded:
lion jpeg_en
Decoded:
lion jpeg_en jpeg_dec

Another Sample at 100:
Original:
mobile
Encoded:
mobile jpeg_en
Decoded:
mobile jpeg_en jpeg_dec

**Comment by Aniq55** [comment]
@arulthileeban the problem still exists. Try this instead: convert a jpeg to png, encode/decode and then convert back to jpeg

**Comment by arulthileeban** [comment]
Thank you . Modified to do the same.
Encoded:
lion jpeg_en

Decoded:
lion jpeg_en png_dec

**Pull request merged**
